# Generated by Django 4.0.1 on 2022-01-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image_file', models.ImageField(db_index=True, height_field='height', upload_to='original_images', width_field='width')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResizedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image_file', models.ImageField(height_field='height', upload_to='responsive_images', width_field='width')),
                ('crop', models.CharField(max_length=10)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsive_images.originalimage')),
            ],
            options={
                'unique_together': {('original', 'width', 'height', 'crop')},
            },
        ),
    ]
